currentBuild.displayName = "Maven-Project-#"+currentBuild.number

pipeline {
    agent any
    stages {
	     stage('Git Checkout'){
            steps{
                url: 'https://github.com/yamuna-bhavani/CI-CD-multi-project-build.git'
                print"Check out completed"
            }
        }
        stage('Maven Clean'){
            steps{
                script{
                    def mavenHome= tool name: 'maven3', type: 'maven'
                    def mavenCMD= "${mavenHome}/bin/mvn"
                    sh "${mavenCMD} compile"
                }
            }
            
        }
        
        stage('Build'){
        steps{
            bat 'mvn install main-project/pom.xml'
         }
        }
        stage('codereview-pmd') {
	   steps {
                echo 'codereview..'
		bat label: '', script: 'mvn -P metrics pmd:pmd'
           }
	   post {
               success {
                   pmd canComputeNew: false, defaultEncoding: '', healthy: '', pattern: '**/pmd.xml', unHealthy: ''
               }
           }		
        }
        stage('unit-test') {
	   steps {
                echo 'codereview..'
		bat label: '', script: 'mvn test'
           }
	   post {
               success {
                   junit 'target/surefire-reports/*.xml'
               }
           }			
        }
        stage('metric-check') {
	   steps {
                echo 'unit test..'
		bat label: '', script: 'mvn cobertura:cobertura -Dcobertura.report.format=xml'
           }
	   post {
               success {
	           cobertura autoUpdateHealth: false, autoUpdateStability: false, coberturaReportFile: 'target/site/cobertura/coverage.xml', conditionalCoverageTargets: '70, 0, 0', failUnhealthy: false, failUnstable: false, lineCoverageTargets: '80, 0, 0', maxNumberOfBuilds: 0, methodCoverageTargets: '80, 0, 0', onlyStable: false, sourceEncoding: 'ASCII', zoomCoverageChart: false                  
               }
           }		
        }
   stage('Sonarqube') {
      environment {
        scannerHome = tool 'sonar-6'
    }
     steps {
        withSonarQubeEnv('Sonarqube') {
            bat label: '', script:'mvn sonar:sonar'
        }
       
    }
}
        stage('package') {
	   steps {
                echo 'metric-check..'
		bat label: '', script: 'mvn package'	
           }		
        }
	stage('Deploy to Nexus'){
	   steps{
	    script{
	       nexusArtifactUploader artifacts: [[artifactId: 'addressbook', classifier: '', file: 'target/addressbook.war', type: 'war']], credentialsId: 'nexus', groupId: 'com.edurekademo.tutorial', nexusUrl: 'localhost:8081', nexusVersion: 'nexus3', protocol: 'http', repository: 'Maven-Project', version: '2.0'
	   }
	 }
	}
    }
}
